### PR TITLE
Nested proptypes working

### PR DESCRIPTION
**Pull request by okanji**
Tested to four levels deep, should work for n levels. 

image

image

### CODE REVIEW

**Comment by mccullochk** [comment]
First off, thanks for spending so much time on this! You obviously have a much better understanding of it than I do but just looking at the `.propTypes` declaration, this is what I would expect the output to look like:

proptype-traversal-comments

It's not at all a big issue. What you have printing out currently is completely valid. I just thought I'd throw it out there, possibly as something to consider for future iterations.

Also, just because that is what I would want to see doesn't mean it is actually the correct output. @chadfawcett, what are your thoughts on those lines. They just feel like duplicate entries to me..

**Comment by mccullochk** [comment]
Also, anyone know why `Storybot` is still pending?

**Comment by chadfawcett** [comment]
Hmm I see what you mean @mccullochk, before it used to be displayed as `oneOfType(node|shape)` etc. I would think if those lines were to be removed, then the following lines would need to be changed from `children/onOfType/shape` to `children/shape` for example. Although those lines are the only ones that show the option of `node`. So I feel like that line would actually just show
`| children/oneOfType | node | no | ...` which seems a bit odd. I think the oddness just comes from the fact that it's displaying as a table. Now that we're running into these issues it might be worth considering a different approach of displaying.

I think this is good for now as is though! I think the oddness is mostly because of the table, and not anything to do with the new code. It might take a bit to get used to, but I feel the information **is** all there, which is a huge improvement to what it currently does.

I think we should merge this in, as it does fix #14. Then later down the road we can look into other ways of displaying the info, if need be.

P.s. I'm not sure why Storybot was stuck pending, but our public repo deployment is broken since [rawgit](https://rawgit.com/) deprecated their service. I've disabled it on this repo for now.

**Comment by okanji** [comment]
Thanks @mccullochk for your feedback! 

1. _Switching the order of those two rows:_

Thats a good observation, it would have been nice in this case if **children/oneOfType/shape** were one row below such that it lies directly above its children. Currently, those rows are being rendered from the unvisited queue in the order that they were enqueued, which is simply the order in which they were set in the Button.PropTypes in the react app. 

I don't think re arranging the two rows would be a good solution for all cases and here is why:

Consider a case where you had two or more types nested two or more levels deep within a **oneOfType**, then even if you were able to arrange them, the best you could do would be to have only one of those types directly above its children: 

image

A better solution, one which would also give you the output that you wanted in the original case that you annotated on, may be to perform a _depth first_ search two levels deep if a node is of type shape (then continue with a _breath first_ search as is currently been used). This will show all the nested nodes of the shape before moving onto any adjacent nodes.

This is what the output would be:
image

And here is an illustration of the method as described above:

image

I think this would be super interesting to implement, if not now then certainly later if we decide that this would be a better way to represent nested objects.

2. _Removing those lines_

In a way it is double entry as everything in the second column of those lines can be inferred from the next few lines but perhaps its nice that you can see what the oneOfType contains without having to look at the lines below. It also means that any types with the oneOfType that don't have further nesting (e.g string, bool, number ...) are printed together on that line and therefor don't need to be printed on separate lines, this condenses things which I think is kind of nice.

**Comment by mccullochk** [comment]
@okanji and @chadfawcett. I appreciated the detailed responses. 

@okanji, I agree with you, the better output would be the second option you mentioned, with the depth first search, but as you and @chadfawcett have already stated it's definitely more something to consider in the future given that right now this **does** show all of the information we need and fixes the current issue.

I'm happy to see this merged in as is! :shipit:

**Review by chadfawcett — APPROVED** [review]
@okanji Feel free to merge this whenever. Just ignore the Storybot pending status.

**Pull request merged**
