### PR TITLE
Show nested props

### PR DESCRIPTION
**Pull request by calebissharp**
Render nested props using a `parent/child/grandchild` format for the `name`.

### CODE REVIEW

**Comment by calebissharp** [comment]
Fixes #9

**Comment by chadfawcett** [comment]
@calebissharp Code looks good, could you throw a screenshot up here?

**Comment by calebissharp** [comment]
How about this:

storybook-screen

**Comment by mccullochk** [comment]
This looks pretty good @calebissharp! Is it possible to get the empty description areas to still display with table formatting?

**Comment by calebissharp** [comment]
I don't know why it doesn't leave an empty area. I think it possibly has something to do with just how the markdown renderer works though. It was actually an issue before, so it might make more sense to have a separate PR.

**Comment by mccullochk** [comment]
Good point, I've opened up https://github.com/TwoStoryRobot/storybook-addon-docgen/issues/11 to address the description area issue.

**Comment by chadfawcett** [comment]
Look good! Thanks @calebissharp

**Comment by mccullochk** [comment]
Thanks @chadfawcett and @calebissharp for working on this!

**Comment by chadfawcett** [comment]
Deployed v1.0.5 to npm

**Pull request merged**
